# Perfil activo dentro del contenedor de aplicacion (Sprint 4), cuando
# app-mtc corre en la misma red Docker (red-mtc) que postgres-mtc.
spring.datasource.url=jdbc:postgresql://postgres-mtc:5432/bd_asesor_turistico
spring.datasource.username=admin_mtc
spring.datasource.password=mtc2026

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.thymeleaf.cache=true

server.port=8082
